# Generated by Django 6.0.2 on 2026-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllog',
            name='started_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='crawllog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=10),
        ),
    ]
