# Generated by Django 6.0.2 on 2026-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
